### ISSUE TITLE
Heroic Dunegon - Azjol Nerub - Anubar Crushers out of position.

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#1]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
All 3 Anub'ar Crushers in Azjol Nerub before Hadronax are incorrectly placed. One is currently off to the side the base of the ramp from the first boss' room.
The other two are two close together so when one is pulled both groups are pulled.

Expected behaviour: Tell us what should happen instead
The first Anub'ar Crusher should be in approximately the center of the room below the web ramp from the first boss' room.
When it is pulled the other two Anub'ar crushers and their supporting adds should spawn and move to positions near the base of each set of steps up to where the small adds who are attacking hadronax continuously spawn.

Steps to reproduce the problem:

1. Enter AN and kill first boss.

2. Proceed down web ramp to encounter first Anub'ar Crusher in incorrect position.

3. Kill Anub'ar Crusher and attempt to engage one of the other Anub'ar Crushers, Both will engage.

4.

**Comment by NexusWoW** [comment]
Fixed pending core update. Thanks!
