### ISSUE TITLE
Heroic Dungeon - Halls of Lightning - General Bjarngrim patrol path

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#10]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
General Bjarngrim, the first boss in H-HoL is currently patrolling an incorrect path.

I have attached an image showing where he is currently patrolling and where he should be patrolling.
![general bjarngrim](https://cloud.githubusercontent.com/assets/25239879/22171680/49c10a40-dfe7-11e6-81bb-f09a63a56e80.png)

**Comment by NexusWoW** [comment]
https://github.com/NexusWoW/NexusWoW/commit/0b90a0282af1f68f11e2fbd794ce16ac758d798c
