### ISSUE TITLE
Heroic Dungeon - Drak Theron Keep Dead mobs going for help

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#11]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
When in H-DTK the two mobs named Risen Drakari Warrior at the north end of the Hall of Departure, when killed, fled emoting "Help mon! There's too many of dem!" and "Backup, We need Backup" adds from the passageways at the top of the stairs then ran down to engage the party.

Expected behaviour: Tell us what should happen instead
This should happen when the pull prior to these mobs is engaged. Not when they are killed.

Steps to reproduce the problem:

1. Go into HDTK

2. Clear up to second last pull in the Hall of Departure.

3. Pull second last group of mobs. Last pull should flee up stairs at this point.

4. Kill second last group of mobs.

5. Pull and kill last 2 mobs (Risen Drakari Warrior).

6. After htey are dead the warriors will move up the stairs (as corpses) and adds will come and engage you.

Include proofs for this behaviour
https://www.youtube.com/watch?v=rmXHHIbEzYQ
At about 3:40 you can see the player engage the second last group of mobs and then the last group runs to get the adds and remains at the end of the corridor waiting for the player to engage them.

**Comment by NexusWoW** [comment]
Thanks Kail, I can't seem to replicate this since the latest core rev. must be fixed :)
