### ISSUE TITLE
Heroic Dungeon - Drak Tharon Keep - Tharon'ja Encounter

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#12]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
The Prophet Tharon'ja periodically brings up the cast bar for "Rain of Fire", but nothing occurs.

Expected behaviour: Tell us what should happen instead
He should cast "Rain of Fire" on an area/player causing an animation of falling fire (like the warlock one) and damage to players in this area.

Steps to reproduce the problem:

1. Engage the Prophet Tharon'ja in Heroic DTK.

2. Wait for him to cast Rain of Fire.

Include proofs for this behaviour
 
Wowwiki http://wowwiki.wikia.com/wiki/The_Prophet_Tharon'ja
"Rain of Fire: Channeled AoE dealing damage in a selected area for 1850 to 2150 Fire (Heroic: 3700 to 4300) damage every 2 seconds for 6 seconds."

**Comment by h0rs** [comment]
Hey @kailective,

Can't reproduce this one:

Normal: http://puu.sh/tGIr1/8ace96a3c9.jpg
Heroic: http://puu.sh/tGIzM/211af57934.jpg

Perhaps the new core will fix this?

@NexusWoW anything you might know?
