### ISSUE TITLE
Heroic Dungeon - Ahn'Kahet, The Old Kingdom - Amanitar encounter

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#13]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
You engage Amanitar in H-OK and he casts mini and mushrooms spawn about the area. The mushrooms are not targetable or damageable by aoe.

Expected behaviour: Tell us what should happen instead
You engage Amanitar in H-OK and he casts mini and mushrooms spawn about the area the healthy mushrooms should be targetable and killable and remove the debuff mini.

Steps to reproduce the problem:

1. In H-OK, clear trash around Amanitar and then engage him.

2. Attempt to kill healthy mushrooms.

Include proofs for this behaviour
Wowwiki article: http://wowwiki.wikia.com/wiki/Amanitar 
"Killing a healthy mushroom when you are "mini" and close to it removes the debuff and appears to be the key to the encounter. Healing through crit chains is very difficult depending on your tank type - dodge-based druids fare better than defense-based prot warriors."

**Comment by NexusWoW** [comment]
@h0rs see https://github.com/TrinityCore/TrinityCore/commit/139a9533256e0312e06fb72cb30622545629f161

**Comment by NexusWoW** [comment]
Issue has been escalated. in the meantime, the boss has had its health reduced by 50% to make it engage-able. this is not a permanent solution, and will be fixed.

**Comment by NexusWoW** [comment]
Fixed!
