### ISSUE TITLE
Heroic Dungeon - Ahn Kahet, The Old Kingdom - Ahn'kahar Spell Flinger

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#14]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
In H-OK the Ahn'kahar Spell Flinger's (http://wotlk.openwow.com/npc=31443) abillities are bugged.
Shadow Sickle currently does nothing beyond generate a cast bar.
Shadow Blast is hitting for ~ 60 damage.

Expected behaviour: Tell us what should happen instead
Shadow Sickle - Sorry, can't find exact values, but it hit rapidly for decent damage, at least 500-1500 I think?
Shadow Blast should hit for 80% of the target's health.

Steps to reproduce the problem:

1. Enter H-OK

2. Clear up to an Ahn'kahar Spell Flinger.

3. Engage Ahn'kahar Spell Flinger and wait for it to cast its spells, observe the minimal damage it inflicts.

Include proofs for this behaviour
Shadow Blast from Wowhead comments; 
http://www.wowhead.com/npc=30278/ahnkahar-spell-flinger#comments
"By tasuki (2,639 – 4·30) on 2010/04/20 (Patch 3.3.3)		
These mobs cast a spell that is a huge percentage-based attack and that no matter how easy you find other heroics these mobs can always two-shot any tank (even if they are crit-capped since its not a crit) regardless of their gear! You can never outgear them. Please don't take them lightly for the sake of your (probably already strained) group's sanity in Old Kingdom.

Specifically:
Shadow Blast
40 yd range
6 sec cast
Hurls a bolt of dark magic at an enemy, inflicting Shadow damage equal to 80% of the target's maximum health.
Last edited by tasuki on 2010/04/20 (Patch 3.3.3)"

**Comment by h0rs** [comment]
Shadow Blast is a relatively easy fix.

However, I'm not sure on the spell mechanics of Shadow Sickle. Would you happen to know if any similar spells that function correctly?

I'm talking about a case where a unit channels a spell while another spell damages other players -- if that makes sense?

**Comment by kailective** [comment]
Possibly the Discipline spell penance?
http://wotlk.openwow.com/spell=53003 is channelled whilst http://wotlk.openwow.com/spell=53000 damages the target.
Or do you need an example from an NPC?

**Comment by h0rs** [comment]
Hey @kailective,

Was thinking something a bit more mechanically complex :)

Basically the way that Shadow Sickle works is that one spell is being channeled that periodically triggers another spell. My assumption is that the triggered spell just hits players at random. Is this true? Should the channel hit multiple people or one person?

Cheers,
h0rs.

**Comment by kailective** [comment]
The comments about it suggest that it is at random enemies, however I don't know of any similar spells in WotLK.

**Comment by h0rs** [comment]
Hey @kailective,

This *should* be fixed. Both spells seem to function correctly.

@NexusWoW can you verify these are the spells casted by those NPCs in the database?

Shadow Sickle
		// http://www.wowhead.com/spell=56702
		// http://www.wowhead.com/spell=59103

Shadow Blast
		// http://www.wowhead.com/spell=56698
		// http://www.wowhead.com/spell=59102

The NPC: http://www.wowhead.com/npc=30278/

The spells have been fixed in the core for those spell IDs :)
