### ISSUE TITLE
Dual talent not switching with ported toons frm Aussiewow

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#15]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
Using the characters which have been ported over from Aussiewow and has dual spec already I have attempted to change to a secondary talent spec. Click the button, toon starts animating, no cast bar, no change of spec, toon just continues animating forever.

Expected behaviour: Tell us what should happen instead
Click the change spec button, toon should commence animating, cast bar should appear, spec should change at completion of cast bar.

Steps to reproduce the problem:

1. Log onto a character with dual spec which has been ported from Aussiewow.

2. Attempt to change spec,

Note: Tested with a toon created on this server, purchased dual spec and he could switch no problem.

**Comment by NexusWoW** [comment]
Will be fixed on final port/release. thanks Kail :)
