### ISSUE TITLE
Naxx 10 - Instructor Razuvious Encounter

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#16]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
When using the Orb of Domination to control to the Death Knight Understudies, if understudy is dismissed (eg. because Forced Obediance is about to run out and you need to reinitiate it before it is your turn to tank) it will despawn. This effectively puts a 1:30 enrage timer on this encounter as that is the duration of a single Forced Obediance.
 
Expected behaviour: Tell us what should happen instead
Understudy should return to being hostile once dismissed from player control.

Steps to reproduce the problem:

1. At Instructor Razuvious, use an Orb of Domination to control a DK Understudy.

2. Right click and dismiss controlled understudy. It will despawn.

Include proofs for this behaviour
http://wowwiki.wikia.com/wiki/Instructor_Razuvious

**Comment by NexusWoW** [comment]
Potentially fixed pending test on reboot. more testing required.

**Comment by kailective** [comment]
Tested this today.
Still bugged.
Also, allowed one of the taunt durations to run out naturally, when this occurs the understudy is released and does not despawn.
