### ISSUE TITLE
10 Man Raid - Ulduar - Flame Leviathan Shutdown

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#17]
**Description**:
Flame Leviathan doesn't go into Shutdown when turrets are destroyed.

**Current behaviour**: Tell us what happens
If a player is launched onto FL he/she can target and destroy the turrets on FL as expected. However, destorying these turrets currently causes no effect, 

**Expected behaviour**: Tell us what should happen instead
Destroying the turrets should cause FL to become stunned, increase its damage taken by 50% and reset its gather speed buff.

**Steps to reproduce the problem**:

1. Engage FL.
2. Launch player onto FL.
3. Player destroys turrets.

http://wowwiki.wikia.com/wiki/Flame_Leviathan

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by NexusWoW** [comment]
Potentially fixed awaiting confirmation on wednesday night!
