### ISSUE TITLE
Paladin - Greater Blessings on pets

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#19]
**Description**:
If you cast a Greater Blessing on a pet, it applies to the Paladin as well and vice versa.

**Current behaviour**: Tell us what happens
When a Paladin casts a Greater Blessing (Eg. Greater Blessing of Sanctuary) upon himself, he gets the buff, but so do any pets of other raid members, eg. warlock imp, hunter pet.
If a paladin casts a Greater Blessing upon a pet in the raid group the buff is applied to the Paladin class as well.
This is annoying because often a paladin will want to cast a different buff on pets to the one for the paladin class.

**Expected behaviour**: Tell us what should happen instead
A paladin casting a Greater Blessing upon himself should apply that blessing only to the paladin class, not pets of raid members.
A paladin casting a Greater Blessing upon a pet in the group should apply that blessing only to pets in the group, not paladins and himself.

**Steps to reproduce the problem**:

1. Group a paladin with a warlock/hunter with their pet out.
2. Cast Greater blessing of might on paladin, it will go on pet and paladin.
3. Cast Greater blessing of wisdom on pet and it will go on pet and paladin,

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by h0rs** [comment]
Hey @kailective,

Thanks for this report, I was able to track down the issue and I *think* the referenced commit should fix it.

I've tested this to the best of my ability.

Commit: https://github.com/NexusWoW/NexusWoW/commit/d527c443375dcd3bedf68c3c3eee7f28dd46653c

Cheers,
h0rs.
