### ISSUE TITLE
Heroic Dungeon - Azjol Nerub - Anub'arak encounter

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#2]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
The final boss of AN, Anub'arak, does not summon the correct numbers of adds when he burrows.
Currently he is summoning 1x Anub'ar Guardian (http://wotlk.openwow.com/npc=31599) and then 1x Anub'ar Venomancer (http://wotlk.openwow.com/npc=31607) each time he burrows.
These adds come down the ramp correctly and behave correctly when engaged.

Expected behaviour: Tell us what should happen instead
The first time he burrows he should spawn 2x Anubar Guardians.
The second time he burrows he should spawn 2x Anub'ar Guardians and then 2x Anub'ar Venomancers.
The third time he burrows he shouldspawn 2x Anub'ar Guardians and then 2x Anub'ar Venomancers.

Steps to reproduce the problem:

1. Engage Anub'arak in Heroic Azjol Nerub.

Include proofs for this behaviour
Sample of fight from 2009, you can see the adds spawn https://www.youtube.com/watch?v=35IVRkmyEFI
Explanation of fight from wowwiki http://wowwiki.wikia.com/wiki/Anub%27arak_(tactics).

**Comment by NexusWoW** [comment]
Fixed pending core update :) thanks :)
