### ISSUE TITLE
LoS Not functioning 

### ISSUE THREAD

**Issue by Jimmeh93** [NexusWoW/Nexus-WoW#21]
Not sure if this has been said, but when LoS'ing a range mob, they shoot through the suppose to be solid object for them to run around to you
The quillboars just north of Camp T (geomancers, hunters)

**Comment by NexusWoW** [comment]
Hey Jimmeh :) thanks. just waiting for more reports to confirm its not global.

**Comment by h0rs** [comment]
Seems to be working okay, at least around hard objects like houses etc.

@Jimmeh93, this is also proven by https://github.com/NexusWoW/Nexus-WoW/issues/20 that LoS stopped you from receiving those buffs.

Going to label this as cannot confirm.

**Comment by Jimmeh93** [comment]
ahh yeah, righto, well when it go lives on the 1st, i will go back there and try again, cause i did try with the cage opened and closed for the buffs but had no result there, ill try hoping inside his cage and see haha

**Comment by Jimmeh93** [comment]
i will test it on launch, just read the #20, good job 😃
