### ISSUE TITLE
RE: Lost bank bag slots from transfer

### ISSUE THREAD

**Issue by Samartok** [NexusWoW/Nexus-WoW#22]
Lost all my bank bag slots on 3 of my toons that had them

Username: Martok
Characters:
Morticus 5 bank slots lost
Martok 6 bank slots lost
Mortador 2 bank slots lost

**Comment by NexusWoW** [comment]
Heya, please open a ticket in game with this exact info :)

**Comment by h0rs** [comment]
@NexusWoW / @Samartok I'll close this off.
