### ISSUE TITLE
unable to pick up quest after dropping. Master of Transmutation - 

### ISSUE THREAD

**Issue by Ambrai** [NexusWoW/Nexus-WoW#23]
**Description**:  Cant pick up any of the Alchemy specialist quests (Elixir, potion or transmute) after dropping one and deciding to do another. It will not let you pick up any of the three options 

**Current behaviour**: All three quest givers no longer have the option to pick up their respective quests

**Expected behaviour**:   See : http://www.wowhead.com/quest=10899/master-of-transmutation

**Steps to reproduce the problem**:

1.  talk to any of the quest givers, no sauce =[
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by h0rs** [comment]
@NexusWoW 

Possibly database related?

**Comment by Ambrai** [comment]
It was a carry over from the previous server h0rs. I just didn't worry about it until moving to the new server
