### ISSUE TITLE
Thistlefurs-Ashenvale

### ISSUE THREAD

**Issue by Jimmeh93** [NexusWoW/Nexus-WoW#24]
Thistlefurs at the Thistlefur Hold Entrance, bug out when they run away, they go underground and reset

**Comment by h0rs** [comment]
Hey @Jimmeh93,

Interesting! I couldn't get them to reset, but some of them certainly go underground.

@NexusWoW, I'm going to hazard a guess and say this is probably collision related.

**Comment by Jimmeh93** [comment]
yea, i started to notice they didnt fully reset until a min or 2 after they went silly :D
