### ISSUE TITLE
Hellfire Fortifications-HFP

### ISSUE THREAD

**Issue by Jimmeh93** [NexusWoW/Nexus-WoW#25]
none of the capture points are capturable, no bar progress of capture pops up either
![wowscrnshot_013017_165843](https://cloud.githubusercontent.com/assets/25411653/22414734/a47b67be-e70d-11e6-8a8a-ba76d80d224e.jpg)

**Comment by h0rs** [comment]
Hey @Jimmeh93 ,

This may be a silly question but are you PvP flagged?

Aprat from that, this seems to works relatively okay on my test branch. It seems to be missing the direction indicators though. The direction indicators function correctly on my old project, perhaps just an issue with the code.

**Comment by Jimmeh93** [comment]
hmm you may be correct on the pvp part,also assumed it automatically flags ya

**Comment by h0rs** [comment]
Hey @Jimmeh93,

Unsure for the live server, my server did not :)

I've written a fix that will indicate the direction the progress bar is heading in any case, so (in the rare event) if contested, the indicators will now show up and let the players know which faction is winning the point.

Fix in: https://github.com/NexusWoW/NexusWoW/commit/f2bc4d421b0c60d1155755c5765ab295ae1f357f

**Comment by Jimmeh93** [comment]
awesome as, cheers dude 😃 
i can test now and see

**Comment by h0rs** [comment]
Hey @Jimmeh93 ,

I'm here on the live server and it seems to work fine :)

I had to flag myself, but I receive a message in my chat window to do so.

I'm going to close this one off mate.

Cheers,
h0rs.

**Comment by Jimmeh93** [comment]
no worries dude, confirm it does work now 😃
