### ISSUE TITLE
Fargodeep Mine [Minor Bug]

### ISSUE THREAD

**Issue by exortelemental** [NexusWoW/Nexus-WoW#26]
**Description**:Minor Bug involving a kobold

**Current behaviour**: Doesn't do anything. Cannot be attack. Doesnt aggro.

**Expected behaviour**: Same as above

**Steps to reproduce the problem**:

1. Coordinates are at 40.76 81.06 at Fargodeep Mines, Elwynn Forest
2. 
3. 

**Branch(es)**: No idea

**AC hash/commit**:  No idea

**Operating system**:  Windows 10

**Modules**:  No

**Other Customizations**: ELVui

**Comment by h0rs** [comment]
@exortelemental,

Can you screenshot this?
