### ISSUE TITLE
Fishing bug

### ISSUE THREAD

**Issue by Samartok** [NexusWoW/Nexus-WoW#27]
Cannot loot anything that is fished up, tried with auto loot both on and off.

Tried in Dalaran and Dragonblight, was able to successfully fish up and loot an imperial manta ray from a school in Dragonblight but anything else that is fished up from the same school will not loot properly and give no skill up.

When the float moves and i right click on it, it brings up the loot window then when I try to loot the item  (or autoloot happens), the interupted message appears on screen, the loot is not in inventory and no skill up is received.

**Comment by h0rs** [comment]
Hey @Samartok,

Thanks for your report.

I was able to find and fix the defect with the skillup, but unfortunately I cannot reproduce the issue you are having in regards to not being able to loot.

I tested this at Moa'ki Harbor using the Imperial Manta Ray pools and was able to retrieve crystallized water, imperial manta rays, etc.

Could you try doing this without any addons enabled just to test?

Fix for skillup chance: https://github.com/NexusWoW/NexusWoW/commit/b23dc2ee8c8fddb212515e6b1b25ee9562fe44fd
