### ISSUE TITLE
Quest: Convocation at Zol'Heb

### ISSUE THREAD

**Issue by Adz82** [NexusWoW/Nexus-WoW#29]
**Description**: 	Prophet of Akali Convocation does not summon prophet of Akali 

**Current behaviour**: When standing in summoning circle, trying to cast Prophet of Akali Convocation it simply wont cast. 

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by h0rs** [comment]
Hey @Adz82,

Thanks for your report. I was able to reproduce this and I've written a fix for next core update.

Commit: https://github.com/NexusWoW/NexusWoW/commit/3f3987023b933166b151b3d19e7f5cb59961d129
