### ISSUE TITLE
Bug - Icecrown Daily Quest - Shoot 'Em Up (13069)

### ISSUE THREAD

**Issue by Protocol25** [NexusWoW/Nexus-WoW#3]
Quest does not register Jotunheim Proto-Drake kill

Quest requires shooting 15 Jotunheim Proto-Drakes. Quest does not register Jotunheim Proto-Drake deaths when killed.

Steps to reproduce the problem:

1. Obtain daily quest from The Leaper at The Shadow Vault 

2. Travel to quest loaction. Mount Jotunheim Rapid-Fire Harpoon at quest location

3. Shoot Jotunheim Proto-Drake

4. Quest log does not register Jotunheim Proto-Drake kill

Quest ID: 13069

**Comment by NexusWoW** [comment]
Fixed pending reboot :)
