### ISSUE TITLE
Dungeon reset - Unable to reclaim corpse

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#33]
**Description**:
If you die in a dungeon, release and then the dungeon resets (3pm server time i think) you will be unable to return to the dungeon to reclaim your corpse.

**Current behaviour**: Tell us what happens
Currently if you attempt to reenter a dungeon following the automatic dungeon reset you get a message saying something like Your corpse does not exist in this instance.

**Expected behaviour**: Tell us what should happen instead
You should regain your corpse but not zone into the new dungeon.

**Steps to reproduce the problem**:

1. Die in a dungeon and release
2. Wait for dungeons to reset at 3pm
3. Attempt to zone back in.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by h0rs** [comment]
Hey @kailective,

Thanks for the report. I was able to reproduce the issue and fix it so you will now be able to retrieve your corpse from its original map, even if the instance no longer exists.

Cheers,
h0rs.
