### ISSUE TITLE
'Love is in the air' event not activating.

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#34]
**Description**:
Currently the dungeon encounter "The Crown Chemical Co." does not activate when in the dungeon.

**Current behaviour**: Tell us what happens
You can que and enter the dungeon following normal process, however, when you attempt to start the event there is no ability to do so.

**Expected behaviour**: Tell us what should happen instead
When you speak to Apothecary Hummel, there should be some kind of option which turns the three apothecaries hostile for the part to defeat.

**Steps to reproduce the problem**:

1. Que "The Crown Chemical Co." in the Dungeon Finder.
2. Attempt to start the event with Apothecary Hummel.
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by h0rs** [comment]
SQL required:

`insert into gossip_menu_option values (10847, 1, 0, 'Begin the battle.', 1, 1, 0, 0, 0, 0, '')`

**Comment by h0rs** [comment]
Hey @kailective,

This should be fixed after a core update.

Cheers,
h0rs.
