### ISSUE TITLE
Crushing the Crown (Love is in the Air)

### ISSUE THREAD

**Issue by Jimmeh93** [NexusWoW/Nexus-WoW#35]
Quests tells me to go kill 5 Crown Sprayers and Destroy the Chemical Wagon with Snagglebot's Khorium Bomb in Cyrstalsong Forest

After slaying the 5 Crown Slayers (that stood no chance against a mighty warrior as myself 😉 ) I attempted to use the bomb on the Chemical Wagon, but it kept coming up with "You cant do that yet" no matter what angle, up top or on bottom of the wagon and range, it still wouldn't work.

![wowscrnshot_020617_140637](https://cloud.githubusercontent.com/assets/25411653/22634606/14fd7270-ec77-11e6-8095-4e13150fb8a4.jpg)

I have addon installed called quest helper, i assumed it would be the cause the problem but tested it with it on and off but same result.

**Comment by h0rs** [comment]
Hey @Jimmeh93,

I've written a fix for this and it should be working after the server is updated.

Cheers,
James.
