### ISSUE TITLE
Recruit A Friend - Unable to Grant Levels

### ISSUE THREAD

**Issue by RandomAkshun** [NexusWoW/Nexus-WoW#37]
**Description**:Unable to grant levels from Recruit a Friend

**Current behaviour**: The ability to grant levels via Recruit a Friend is not available from the drop down menu when right clicking on a friend's icon.  GM Violet was notified and she advised to post here.

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by h0rs** [comment]
Hey @RandomAkshun,

Thanks for your report! I've reviewed this ticket and implemented a fix for it. This should take effect after the server is updated.

Cheers,
h0rs.

Reference commit: https://github.com/NexusWoW/NexusWoW/commit/5c20cab442d283e423aa244d29c3e0ceaaf791b9.

CC @NexusWoW

**Comment by NexusWoW** [comment]
woot!
