### ISSUE TITLE
Bug - Game Crash

### ISSUE THREAD

**Issue by Protocol25** [NexusWoW/Nexus-WoW#4]
Dalaran Barber Shop, character sits in barber chair, scrolls hair cut options, game crashes.

Crash replicated four successive times. All addons disabled, WTF and Cache folders deleted from WoW directory.

Steps to reproduce the problem:

1. Sit in barber chair in Dalaran barber shop

2. Scroll through haircut options

3. Game crashes

Include proofs for this behaviour

WoW Error Report Attached
[Nexuswow_BarberChairCrash_Ven.txt](https://github.com/NexusWoW/Nexus-WoW/files/718977/Nexuswow_BarberChairCrash_Ven.txt)

**Comment by NexusWoW** [comment]
Unable to replicate, need more confirmed reports :)

**Comment by h0rs** [comment]
Unable to reproduce this myself either.

@Protocol25: Does this occur on other servers, also, have you tried a different 3.3.5 client?
