### ISSUE TITLE
Bug/crash during quest.

### ISSUE THREAD

**Issue by Geliathus** [NexusWoW/Nexus-WoW#40]
**Game Crashing during the quest "Going bearback"**:

**Current behaviour**: game crashes when either; trying to complete quest, or opening game menu during quest. Also can't comlete quest as I can't damage said enemies for quest.

**Expected behaviour**: to burn the enemies listed.
**Steps to reproduce the problem**:

1. Get on the bear
2. hit escape
3. or get off bear, then hit escape or try to abandon quest.

**Comment by NexusWoW** [comment]
Fixed pending reboot, please reopen if not successful :)
sorry it took so long,
Thanks :)
