### ISSUE TITLE
Gurubashi Arena Chest

### ISSUE THREAD

**Issue by luvdemchickens** [NexusWoW/Nexus-WoW#46]
**Description**:
The Gurubashi Arena chest isn't spawning 
**Current behaviour**: Tell us what happens
No RP, or annoucments, or chest spawn at usual time, I have checked the past 3 hours.
**Expected behaviour**: Tell us what should happen instead
Every 3rd hour of the day Gurubashi Arena chest spawns (12pm, 3pm, 6pm, etc.)
**Steps to reproduce the problem**:

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by talamortis** [comment]
this works a player has to be within stranglethron vale when the time happens. the reason it doesnt spawn when a player is not in the zone is to save recources and memory its core side.
