### ISSUE TITLE
Heroic Dungeon - Violet Hold - Reputation

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#5]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
No mobs killed in the Heroic Violet Hold give reputation bonuses when killed.

Expected behaviour: Tell us what should happen instead
All mobs spawned in waves in Heroic Violet Hold should reward reputation when killed.
Bosses - 250 each (see wowwiki article referenced below.)
Can't find precise info on the other mobs sorry. I would imagine they are in line with other instances.
Eg. Portal Guardians/Keepers - 39 each
Azure Sorcerers/Raiders/Stalkers/Captains - 29
Azure Invaders/Mageslayers/Spellbreakers - 19
Sorry, checked everywhere I know, But the only reference I could find with an exact number was from post wotlk (2010).

Steps to reproduce the problem:

1. Enter Heroic Violet Hold.

2. Wait for a wave to spawn. 

3. Kill mobs. No rep.

Include proofs for this behaviour

Wowwiki article (http://wowwiki.wikia.com/wiki/Violet_Hold_(original)) states 
"On Heroic, it awards approximately 1300 reputation.

Upon Death, one must fight through all waves, including the bosses, again. However, in Heroic mode, bosses that have already been defeated are replaced by mobs that are the same but differently named, and provide only 250 Reputation and no loot...."

**Comment by NexusWoW** [comment]
Fixed :) Thanks once again kail, you are irreplaceable :)
