### ISSUE TITLE
Immolate or conflagarate

### ISSUE THREAD

**Issue by billy123455** [NexusWoW/Nexus-WoW#50]
**Description**:
gcd bugged
**Current behaviour**: there is a delay between when immolate casts and when it hits, also you should be able to cast conflagarate straight after in the same gcd but either this is another bug or just caused by delayed immolate

**Expected behaviour**: Immolate should be cast instantly on the target after you cast and you should be able to conflag in the same gcd

**Steps to reproduce the problem**: cast immolate with conflag talented and try it

1. 
2. 
3. 

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

**Comment by NexusWoW** [comment]
this is not an issue, and is in fact blizzlike, see: https://us.battle.net/forums/en/wow/topic/2826023945
Working as intended :)
Thanks for taking the time to report :)
