### ISSUE TITLE
New Characters can not use abilities , or equip items

### ISSUE THREAD

**Issue by Geliathus** [NexusWoW/Nexus-WoW#54]
**Description**: Can't use abilities, or equip anything

**Current behaviour**: When making a new toon, none of the abilities can be used, items can be unequipped but cannot be equipped. 

**Expected behaviour**: To be able to play properly?

**Steps to reproduce the problem**:

1. Create character
2. 
3.

**Comment by h0rs** [comment]
@Geliathus 

Apologies for the late reply but I believe Violetsareblue has tested this and was unable to reproduce.

Could you let me know where you got your client from?

Cheers,
h0rs.
