### ISSUE TITLE
Heroic Dungeon - Utgarde Pinacle - Skadi the Ruthless Encounter

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#7]
Currently:
When Skadi's drake is shot down by the player using harpoons, Skadi jumps into the players zone and any adds who remain instantly despawn leaving the player to face only Skadi. 

Expected:
Adds should not despawn, but should remain to fight the players whilst Skadi is engaged.
New adds should not spawn.

Steps to re-produce:
1) Enter H-UP.
2) Clear up to the Skadi encounter.
3) Clear all waves and adds on the way to the harpoon launchers, collect the harpoons.
4) Ensure adds are up when Skadi is in position to be shot down,
5) Shoot Grauf down, engaging Skadi in combat. Adds will despawn.

Evidence:
From http://wowwiki.wikia.com/wiki/Skadi_the_Ruthless
"Once you have downed the majority of the mobs, during the next boss pass have the person carrying the harpoons shoot the boss down. Then begin to clear remaining adds, and finally the boss. Beware: rushing to the Harpoon end and gathering in the doorway despawns the boss mid-combat."
Implies adds will remain up once skadi is engaged off his drake, hence needing to be cleared.

**Comment by NexusWoW** [comment]
Fixed pending core update :)
