### ISSUE TITLE
Item - Amani Charm of the Bloodletter

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#8]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
Currently the Amani Charm of the Bloodletter (http://www.wowhead.com/item=33930/amani-charm-of-the-bloodletter) if used inside Zul Aman gives the buff Charm of the Bloodletter (http://www.wowhead.com/spell=43816). 
If you leave ZA this buff does not disappear.

Expected behaviour: Tell us what should happen instead
Buff should disappear when leaving ZA.
I have not tested this with the other charms, but have every reason to believe that this would apply to all 'Amani Charm of the ...' items.
http://www.wowhead.com/item=33933/amani-charm-of-the-raging-defender
http://www.wowhead.com/item=33931/amani-charm-of-mighty-mojo
http://www.wowhead.com/item=33932/amani-charm-of-the-witch-doctor
http://www.wowhead.com/item=33933/amani-charm-of-the-raging-defender

Steps to reproduce the problem:

1. Enter Zul Aman

2. Acquire an Amani Charm of the ...

3. Use Amani Charm of the ...

4. Leave ZA. Buff will remain.

Include proofs for this behaviour

Wowhead comment for Amani Charm of the Raging Defender 
http://www.wowhead.com/item=33933/amani-charm-of-the-raging-defender#comments

"By Kathucka (20,928 – 4·30·172) on 2008/09/04 (Patch 2.4.3)		
Using this gives you a buff that does not expire until you leave the instance. You don't equip it. You just use it like an elixir. It is consumed when you use it.

Both the item and the buff disappear if you leave the instance."

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/ Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

Include Screenshots from the issue if necessary

**Comment by h0rs** [comment]
Should be fixed by: https://github.com/NexusWoW/NexusWoW/commit/85325d08e1a6dc2c79605e7dfb3137babdd2b56d
