### ISSUE TITLE
Item - Manual: Heavy Frostweave Bandage dropping too frequently

### ISSUE THREAD

**Issue by kailective** [NexusWoW/Nexus-WoW#9]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
Currently the item Manual: Heavy Frostweave Bandage (http://www.wowhead.com/item=39152/manual-heavy-frostweave-bandage) is dropping from every WotLK heroic boss for every member of the party, regardless of first aid level.

Expected behaviour: Tell us what should happen instead
This item should only drop for characters with 390+ First aid skill.

Steps to reproduce the problem:

1. Kill a Boss in a heroic level 80 dungeon.

Include proofs for this behaviour
Wowhead comment
http://www.wowhead.com/item=39152/manual-heavy-frostweave-bandage#comments
"By Kemian (510 – 1·1) on 2008/11/20 (Patch 3.0.3)		
I can confirm 390 First Aid as being the apparent "required" skill level to have the book drop: I grinded on the aforementioned Drakuru Berserkers for about an hour at 382 First Aid and didn't see it drop. After leveling to 390, however, the book dropped on my third kill. This is consistent with what others are reporting."

**Comment by NexusWoW** [comment]
drop rate was far too high. its been rescaled, as well as entry conditions being reworked. Item should still appear on group loot, but with specific skill requirements. see: https://github.com/TrinityCore/TrinityCore/issues/12004
